CREATE TABLE links(
  id SERIAL PRIMARY KEY,
  short VARCHAR NOT NULL UNIQUE,
  long VARCHAR NOT NULL
);

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL
);
