[package]
name = "linkr"
version = "0.1.0"
authors = ["Liam Rosenfeld <me@liamrosenfeld.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.4.5", features=["private-cookies"] }
diesel = { version = "1.4.4", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
rocket_contrib = { version = "0.4.5", default-features = false, features = ["json"] }
serde = { version = "1.0.111", default-features = false, features = ["derive"] }
serde_json = "1.0.53"
scrypt = "0.2"
