[package]
name = "linkr"
version = "0.1.0"
authors = ["Liam Rosenfeld <me@liamrosenfeld.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.4.5", features = ["private-cookies"] }
dotenv = "0.15.0"
serde = { version = "1.0.111", default-features = false, features = ["derive"] }
serde_json = "1.0.55"
scrypt = "0.3.0"
chrono = { version = "0.4", features = ["serde"] }

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json", "handlebars_templates"]

[dependencies.diesel]
version = "1.4.5"
features = ["postgres", "r2d2", "chrono"]
