CREATE TABLE links(
  id    SERIAL PRIMARY KEY,
  short TEXT NOT NULL UNIQUE,
  long  TEXT NOT NULL
);

CREATE TABLE users(
  id       SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  pw_hash  TEXT NOT NULL
);
